version: 0.2
            
phases:
  install:
    runtime-versions:
      golang: 1.12
    commands:
      - echo "installing"

  pre_build: 
    commands:
      # Ensure code passes all lint tests
      - echo "prebuild"

  build:
    commands:

      # Build our application
      - go build -o application

artifacts:
  files:
    - buildspec.yml
    - go/*