---
Description: Lambda function Automation.
Resources:
  primer:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.8
      FunctionName: test2
      Role: arn:aws:iam::589557565942:role/SQSroleforLambda
      Handler: index.lambda_handler
      Code:
        ZipFile: |
          import boto3
          def lambda_handler(event, context):
   
            ses = boto3.client("ses")
            response = ses.send_email(
                Source='dileep.valluru@gmail.com',
                Destination={
                    'ToAddresses': [
                        'dileep.valluru@hotmail.com',
                    ]
                },
                Message={
                    'Subject': {
                        'Data': 'Check the Queues',
                        'Charset': 'ASCII'
                    },
                    'Body': {
                        'Text': {
                            'Data': 'message are piling up in the so and so SQS queue.Please check the queues',
                            'Charset': 'ASCII'
                        },
                    },
                }
            )
      